-- =============================================
-- Migration 00010: Seed DFW Market & Zip Codes
-- =============================================

-- DFW Metropolitan Area
INSERT INTO markets (name, slug, state, metro_area, is_active, center_lat, center_lng, radius_miles)
VALUES ('Dallas-Fort Worth', 'dfw', 'TX', 'Dallas-Fort Worth-Arlington', TRUE, 32.7767, -96.7970, 60);

-- DFW zip codes (major cities)
-- Dallas
INSERT INTO market_zip_codes (market_id, zip_code, city, county) VALUES
((SELECT id FROM markets WHERE slug = 'dfw'), '75201', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75202', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75203', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75204', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75205', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75206', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75207', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75208', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75209', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75210', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75211', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75212', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75214', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75215', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75216', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75217', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75218', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75219', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75220', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75223', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75224', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75225', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75226', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75227', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75228', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75229', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75230', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75231', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75232', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75233', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75234', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75235', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75236', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75237', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75238', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75240', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75241', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75243', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75244', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75246', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75247', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75248', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75249', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75251', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75252', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75253', 'Dallas', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75254', 'Dallas', 'Dallas'),
-- Fort Worth
((SELECT id FROM markets WHERE slug = 'dfw'), '76101', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76102', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76103', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76104', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76105', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76106', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76107', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76108', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76109', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76110', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76111', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76112', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76114', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76115', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76116', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76117', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76118', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76119', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76120', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76123', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76126', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76129', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76131', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76132', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76133', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76134', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76135', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76137', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76140', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76148', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76155', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76164', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76177', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76179', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76180', 'Fort Worth', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76182', 'Fort Worth', 'Tarrant'),
-- Arlington
((SELECT id FROM markets WHERE slug = 'dfw'), '76001', 'Arlington', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76002', 'Arlington', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76006', 'Arlington', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76010', 'Arlington', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76011', 'Arlington', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76012', 'Arlington', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76013', 'Arlington', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76014', 'Arlington', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76015', 'Arlington', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76016', 'Arlington', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76017', 'Arlington', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76018', 'Arlington', 'Tarrant'),
-- Plano
((SELECT id FROM markets WHERE slug = 'dfw'), '75023', 'Plano', 'Collin'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75024', 'Plano', 'Collin'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75025', 'Plano', 'Collin'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75074', 'Plano', 'Collin'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75075', 'Plano', 'Collin'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75093', 'Plano', 'Collin'),
-- Frisco
((SELECT id FROM markets WHERE slug = 'dfw'), '75033', 'Frisco', 'Collin'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75034', 'Frisco', 'Collin'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75035', 'Frisco', 'Collin'),
-- McKinney
((SELECT id FROM markets WHERE slug = 'dfw'), '75069', 'McKinney', 'Collin'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75070', 'McKinney', 'Collin'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75071', 'McKinney', 'Collin'),
-- Allen
((SELECT id FROM markets WHERE slug = 'dfw'), '75002', 'Allen', 'Collin'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75013', 'Allen', 'Collin'),
-- Irving
((SELECT id FROM markets WHERE slug = 'dfw'), '75038', 'Irving', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75039', 'Irving', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75060', 'Irving', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75061', 'Irving', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75062', 'Irving', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75063', 'Irving', 'Dallas'),
-- Grand Prairie / Garland / Mesquite / Richardson
((SELECT id FROM markets WHERE slug = 'dfw'), '75050', 'Grand Prairie', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75051', 'Grand Prairie', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75052', 'Grand Prairie', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75040', 'Garland', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75041', 'Garland', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75042', 'Garland', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75043', 'Garland', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75044', 'Garland', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75149', 'Mesquite', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75150', 'Mesquite', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75080', 'Richardson', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75081', 'Richardson', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75082', 'Richardson', 'Dallas'),
-- Denton / Lewisville / Flower Mound / Keller / Southlake
((SELECT id FROM markets WHERE slug = 'dfw'), '76201', 'Denton', 'Denton'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76205', 'Denton', 'Denton'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76207', 'Denton', 'Denton'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76210', 'Denton', 'Denton'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75056', 'The Colony', 'Denton'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75057', 'Lewisville', 'Denton'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75067', 'Lewisville', 'Denton'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75028', 'Flower Mound', 'Denton'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75022', 'Flower Mound', 'Denton'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76248', 'Keller', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76262', 'Roanoke', 'Denton'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76092', 'Southlake', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76034', 'Colleyville', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76051', 'Grapevine', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76053', 'Hurst', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76054', 'Hurst', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76039', 'Euless', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76040', 'Euless', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76021', 'Bedford', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76022', 'Bedford', 'Tarrant'),
-- Mansfield / Cedar Hill / Midlothian / Waxahachie
((SELECT id FROM markets WHERE slug = 'dfw'), '76063', 'Mansfield', 'Tarrant'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75104', 'Cedar Hill', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '76065', 'Midlothian', 'Ellis'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75165', 'Waxahachie', 'Ellis'),
-- Rockwall / Rowlett / Wylie / Murphy / Sachse
((SELECT id FROM markets WHERE slug = 'dfw'), '75087', 'Rockwall', 'Rockwall'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75088', 'Rowlett', 'Dallas'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75098', 'Wylie', 'Collin'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75094', 'Murphy', 'Collin'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75048', 'Sachse', 'Dallas'),
-- Prosper / Celina
((SELECT id FROM markets WHERE slug = 'dfw'), '75078', 'Prosper', 'Collin'),
((SELECT id FROM markets WHERE slug = 'dfw'), '75009', 'Celina', 'Collin');
