import { NextRequest, NextResponse } from 'next/server'
import { createClient as createServerClient } from '@/lib/supabase/server'
import { createClient } from '@supabase/supabase-js'

function getSupabaseAdmin() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )
}

// POST /api/orders - Create a new order from the consumer flow
export async function POST(request: NextRequest) {
  try {
    // Verify auth
    const supabase = await createServerClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()

    const supabaseAdmin = getSupabaseAdmin()

    // Resolve service_id from slug
    const { data: service, error: serviceError } = await supabaseAdmin
      .from('catalog_services')
      .select('id, name')
      .eq('slug', body.service_slug)
      .single()

    if (serviceError || !service) {
      return NextResponse.json({ error: 'Service not found' }, { status: 400 })
    }

    // Convert dollars to cents for DB storage
    const basePriceCents = Math.round((body.base_price_dollars || 0) * 100)
    const addonsTotalCents = Math.round((body.addons_total_dollars || 0) * 100)
    const totalCents = Math.round((body.total_dollars || 0) * 100)
    const depositCents = Math.round((body.deposit_dollars || 0) * 100)

    // Platform fee: 10% of subtotal
    const platformFeeCents = Math.round(totalCents * 0.10)
    const contractorPayoutCents = totalCents - platformFeeCents

    // Create order (order_number auto-generated by trigger)
    const { data: order, error: orderError } = await supabaseAdmin
      .from('orders')
      .insert({
        user_id: user.id,
        home_id: body.home_id || null,
        status: 'confirmed',
        subtotal: totalCents,
        platform_fee: platformFeeCents,
        total: totalCents,
        scheduled_date: body.scheduled_date || null,
        scheduled_time_slot: body.scheduled_time_slot || null,
        metadata: {
          tier: body.tier,
          customer_name: body.customer_name,
          customer_phone: body.customer_phone,
          deposit_amount_cents: depositCents,
        },
      })
      .select('id, order_number')
      .single()

    if (orderError || !order) {
      console.error('[Create Order] Order insert error:', orderError)
      return NextResponse.json(
        { error: `Failed to create order: ${orderError?.message}` },
        { status: 500 }
      )
    }

    // Create order item
    const { error: itemError } = await supabaseAdmin
      .from('order_items')
      .insert({
        order_id: order.id,
        service_id: service.id,
        contractor_id: body.pro_id !== 'homework-platform' ? body.pro_id : null,
        service_name: service.name,
        selected_variables: body.selected_variables || {},
        selected_addons: body.selected_addons || [],
        base_price: basePriceCents,
        addon_total: addonsTotalCents,
        line_total: totalCents,
        platform_fee: platformFeeCents,
        contractor_payout: contractorPayoutCents,
      })

    if (itemError) {
      console.error('[Create Order] Item insert error:', itemError)
      // Clean up the order if item creation fails
      await supabaseAdmin.from('orders').delete().eq('id', order.id)
      return NextResponse.json(
        { error: `Failed to create order item: ${itemError.message}` },
        { status: 500 }
      )
    }

    // Copy stage template to order
    const templateSlug = body.service_slug === 'ac-system-replacement' ? 'hvac-install' : 'general-service'
    const { error: stagesError } = await supabaseAdmin.rpc('copy_template_stages_to_order', {
      p_order_id: order.id,
      p_template_slug: templateSlug,
    })

    if (stagesError) {
      console.error('[Create Order] Stages copy error:', stagesError)
      // Non-fatal — order still valid, stages can be added later
    }

    return NextResponse.json({
      orderId: order.id,
      orderNumber: order.order_number,
    })
  } catch (error) {
    console.error('[Create Order Error]', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to create order' },
      { status: 500 }
    )
  }
}

// GET /api/orders - Get all orders for the current user
export async function GET() {
  try {
    const supabase = await createServerClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const supabaseAdmin = getSupabaseAdmin()
    const { data: orders, error } = await supabaseAdmin
      .from('orders')
      .select(`
        *,
        order_items (*),
        order_stages (*)
      `)
      .eq('user_id', user.id)
      .order('created_at', { ascending: false })

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ data: orders })
  } catch (error) {
    console.error('[Get Orders Error]', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to fetch orders' },
      { status: 500 }
    )
  }
}
